### ISSUE TITLE
error with train_svm.py train.csv test.csv --final in svm.py l.190

### ISSUE THREAD

**Issue by EtienneFerrandi** [SupervisedStylometry/SuperStyl#26]
dists[myclass[1]] = [d[myclass[0]] for d in decs]
IndexError: invalid index to scalar variable.

**Comment by Jean-Baptiste-Camps** [comment]
A bit late on this one, but: I could not reproduce the error with the latest version of Superstyl. If you still see it, don't hesitate to tell me. Also, I would need more details !
