### ISSUE TITLE
IndexError when final testing/writing final predictions with two categories

### ISSUE THREAD

**Issue by mailanlopez** [SupervisedStylometry/SuperStyl#31]
`.......... Writing final predictions to FINAL_PREDICTIONS.csv ........`
`Traceback (most recent call last):`
`File "train_svm.py", line 53, in <module>`
` svm = superstyl.svm.train_svm(train, test, cross_validate=args.cross_validate, k=args.k, dim_reduc=args.dim_reduc,`
`File "/SuperStyl/superstyl/svm.py", line 190, in train_svm`
`    dists[myclass[1]] = [d[myclass[0]] for d in decs]`
`File "/SuperStyl/superstyl/svm.py", line 190, in <listcomp>`
`    dists[myclass[1]] = [d[myclass[0]] for d in decs]`
   `IndexError: invalid index to scalar variable.`

**Comment by Jean-Baptiste-Camps** [comment]
A bit late on this one, but: I could not reproduce the error with the latest version of Superstyl. If you still see it, don't hesitate to tell me.
