### ISSUE TITLE
Problem when using SMOTETomek

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [SupervisedStylometry/SuperStyl#64]
````
TypeError: SMOTETomek.__init__() got an unexpected keyword argument 'n_neighbors'
````

**Comment by Jean-Baptiste-Camps** [comment]
@floriancafiero

**Comment by Jean-Baptiste-Camps** [comment]
Floriaaaaaaaaaaaan !!!!!!!!!!!
@floriancafiero 
(Dating from 27 February !)

**Comment by floriancafiero** [comment]
Je crois que je comprends la blague. Je tente quelque chose. Mais j'ai géré de la même manière SMOTE et SMOTETomek je crois.

**Comment by Jean-Baptiste-Camps** [comment]
Hmmm, je me demande si ce n'est pas une question de version de scikit-learn

**Comment by Jean-Baptiste-Camps** [comment]
Should no longer exist. Weird. I'm closing it until it reappears
